adminUser: admin
adminPassword: admin

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin
  auth:
    disable_login_form: true

plugins:
  - quickwit-quickwit-datasource
  - victoriametrics-logs-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Quickwit k8s-logs
        uid: quickwit-k8s-logs
        type: quickwit-quickwit-datasource
        access: proxy
        url: http://quickwit-searcher.observability.svc.cluster.local:7280/api/v1
        isDefault: true
        jsonData:
          index: k8s-logs
          timeField: timestamp
          logMessageField: message
          logLevelField: level
      - name: Loki k8s-logs
        uid: loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
      - name: VictoriaLogs k8s-logs
        uid: victorialogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victorialogs.observability.svc.cluster.local:9428

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards

service:
  type: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 128Mi
